### ISSUE TITLE
pagehits 관련

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#103]
예전에는 기본적으로 조회수가 많은 페이지 순서대로 표시되고, reverse 옵션으로 조회수가 적은 페이지 순서대로 볼 수도 있었는데, 업데이트 이후에는 무슨 기준으로 정렬되는지 파악할 수가 없네요.

**Comment by NbverHub** [comment]
아, 그리고 역링크도 TitleIndex처럼 정렬되서 나오는 건 좋은데, 이전 처럼 몇 개가 있는지 개수를 알 수 있었으면 합니다.

**Comment by wkpark** [comment]
예전 `PageHits()` 매크로는 메이지 개수가 많을때 문제가 있었습니다.

전체 페이지를 모두 가져와서 이를 정렬하니 메모리 소모도 심하거나 하는 등등.

그래서 예전의 매크로는 지정된 개수 단위(기본값 200)로만 일부 가져와서 정렬을 합니다.
따라서 전체적으로 정렬된 순으로 보여주지는 못하고 조금 쓸모 없는 기능이 되어버렸네요.

----
이러한 문제를 이번에 추가된 `PageSort` 매크로를 통해 대치하게 되었습니다.

PageSort는 전체 페이지를 가져와서 히트수로 정렬을 한 후에 이를 따로 저장합니다.
저장된 내용은 일정 시간이 지나야 갱신되며, 전체 문서 개수가 많더라도 속도 및 메모리 소모적인 측면에서 문제 없게 하였습니다.

페이지 히트순으로 보시려면 `?action=pagesort&sortby=hits` 를 주소줄에 넣어보시기 바랍니다.
