### ISSUE TITLE
edge에서

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#105]
edge에서 테이블 테두리 일부가 보이지 않거나, blockquote 배경이 우측에 정렬된 사진을 가리는 문제점이 있는 것 같습니다. 리그베다 위키에서도 확인되는 현상이네요.

Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

버전에서 확인했습니다.

**Comment by wkpark** [comment]
이건 CSS의 `overflow-y:hidden;`때문이더군요. 간단히 없애니 해결되었습니다.

CSS이슈는 테마에 관련된 이슈이므로 테마에서 해결하도록 하고 이를 닫도록 하겠습니다.

참고로 부트스트랩 테마에서는 이 이슈가 해결되었습니다.
