### ISSUE TITLE
부트스트랩3.x 기본 지원

### ISSUE THREAD

**Issue by wkpark** [wkpark/moniwiki#108]
부트스트랩3.x 기본 지원을 위해 필요한 부분을 고칩니다.

부트스트랩3.x 기본 스킨이 별도로 제공될 예정입니다.

**Comment by wkpark** [comment]
현재 가장 완성도가 높은 paper 테마 + 리그베다위키 테마를 바탕으로 하고,
부트스트랩3를 적용한 테마입니다.
https://github.com/wkpark/moniwiki-theme-bootstrap3

기존의 스타일을 거의 그대로 사용했으나, 필요 없는 부분을 걷어내고
부트스트랩을 통해서 스타일의 일관성을 높였습니다.

이 테마는 부트스트랩3를 적용한 것과 거의 다를바 없으며
이를 바탕으로 조금씩 개선할 예정입니다.

**Comment by NbverHub** [comment]
paper대신 이 테마가 기본 테마가 되나요?

**Comment by wkpark** [comment]
> paper대신 이 테마가 기본 테마가 되나요?

부트스트랩을 싫어하시는 분도 계시기때문에, 현재 같이 포함되어 배포되는 `publish` 대신에 포함될 예정입니다. 셋업에서 테마를 고를 수 있게 할 생각입니다.

**Comment by wkpark** [comment]
테마를 고를 수 있게끔 셋업에서 고치는 부분은 다른 이슈로 처리하겠습니다
