### ISSUE TITLE
edge에서 로그인 할 수 없는 현상

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#109]
edge에서 로그인을 시도하면 UserPreferences로 돌아가면서 양식을 다시 제출할까요라고 묻는 알림창이 뜨는데, 다시 제출을 클릭하면 무한 반복되고, 취소를 누르면 로그인이 되지 않습니다.

Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

**Comment by NbverHub** [comment]
부트스트랩에서 시도하니 다시 제출 후 해결되네요. paper 테마만의 문제 같기도 하고..

**Comment by wkpark** [comment]
edge를 쓰지 않아서 정확히 확인하기 어렵네요.

**Comment by wkpark** [comment]
로컬 유저의 경우 쿠키 도메인 문제로 로그인이 안되는 것을  확인하여 수정하였습니다.
이와 다른 문제라면 적어도 최신 개발판 + 최신 edge에서 문제 없음이 확인되었습니다.
