### ISSUE TITLE
모니위키 최신버전에서 로그인이 너무 빨리 풀립니다. 

### ISSUE THREAD

**Issue by icehit3** [wkpark/moniwiki#113]
모니위키 로그인 후 글을 작성하다 보면, 어느새 로그인이 풀려 있습니다. 

체감상 로그인 유지 시간이 5분 정도 밖에 안되는 것 같아요. 

글을 쓰다가 날리는 경우도 있습니다. 

로그인 상태를 계속 유지할 수 있도록 별도 옵션 추가 요청 드립니다.

**Comment by wkpark** [comment]
음... 이것은 쿠키버그가 있는 모양이네요. 혹은 쿠키가 꼬여있거나?

쿠키자체도 별로 안전하지는 않기때문에, 차차 제거/보완하도록 하겠습니다~

**Comment by wkpark** [comment]
꽤 지난 것이지만 답변 답니다.
모니위키 기본 세팅 상태에서는 session을 사용하는데,
세션 쿠키의 expire 기본값이 1시간 (`60*60 = 3600`)이었습니다. 이 기본 값을 24시간으로 바꾸고,
이를 바꿀 수 있는 `$session_lifetime` 옵션을 config.php에 설명달았습니다.
