### ISSUE TITLE
글자색 변경방법에 대하여

### ISSUE THREAD

**Issue by elviraskim** [wkpark/moniwiki#116]
안녕하세요 ?
2003년부터 아주 편리하고 똑똑하고 함께쓰는 메모장(?)으로 사용하는 사용자입니다.
그동안 제가 요청한 것들을 몇가지는 반영되고 안된것(무지해서) 있지만 무지한 부탁인 같은데 강조(''' ''') 기능을 사용하는데 이탤릭('' '') 기능을 사용하지 않습니다. 한글만 사용해서요. 개인적으로 대신 글자의 색상을 지정한 색상으로 변경하고 싶은데 HTML (CSS조금) 밖에 몰라서 도움 요청합니다.
''이텔릭'' 이기능을 지정한(파란색)으로 표시되게 하려면 어떤부분을 어떻게 고치면 되는지 알려주시면 대단히 감사하겠습니다. 나이도 50중반이라 수고스럽겠지만 샘플코드를 만들어 보내주시면 복사해서 붙여넣기는 할 수 있겠습니다.
성경에 해설을 덧붙이다보니 굵은강조만으론 부족해서 칼라강조를 하고싶어서 부탁드립니다.
간편한 몇가지 칼라강조를 할 수 있는 방법이 있으면 좋겠지만 제 실력으로 턱도 없고 이텔릭 대신 한칼라만해도 만족하겠습니다.
이렇게 편리하고 훌륭한 함께쓰는 워드프로세서(?) 만들어 주셔서 늘 감사드리고 있습니다.

**Comment by 2DU** [comment]
{{{#색상 내용}}} 하시면 됩니다

**Comment by elviraskim** [comment]
감사합니다.
이렇게 쉬운걸 그렇게 고민했네요.
다시 한번 감사드립니다.

**Comment by 2DU** [comment]
리그베다 위키의 편집 도움말을 참조하시면 더 쉬울 겁니다

enha.xyz/w/편집%20도움말

**Comment by elviraskim** [comment]
그리베다 위키의 편집 도움말이 정말 도움이 많이 됩니다.
다시 한번 감사드립니다.

**Comment by 2DU** [comment]
옛날에는 제일 큰 위키였는데 고려 왕조 처럼 몰락 해버렸죠 지금와서 되돌아보면 안타깝네요
