### ISSUE TITLE
문단의 첫글자 들여쓰기 방법

### ISSUE THREAD

**Issue by elviraskim** [wkpark/moniwiki#117]
안녕하세요 ?
지난번 글자색 변경에 대한 질문에 답변에 감사드립니다.
위키에서 글쓰기를 할때 문단의 첫글자를 들여쓰기를 하려면 어떻게 해야 합니까?
워드처럼 빈칸을 넣으면 문단 전체가 들여쓰기가 되는데,
문단의 첫줄의 첫글자만 한글자 만큼 들여쓰는 방법을 알려주세요.
혹시 CSS를 변경해야 한다면 샘플코드도 부탁드립니다.
모니위키 개발자분들과 답변주신 분들께 감사드립니다.
그리고 이런 질문이 이슈게시판에 맞지 않는다는 것을 알고 있지만 
지식이 부족한데 마땅히 물어볼 곳이 없어서 올립니다. 죄송합니다.

**Comment by 2DU** [comment]
{{{ }}}내용 이렇게 하면 어떨까요

**Comment by elviraskim** [comment]
답변 감사합니다.
제 위키에서는 {{{빈칸}}} 해도 빈칸이 안되네요.
제가 쓰고 있는 방법은 특수문자 중에 한글종성필터(U+115F) 클립보드에 복사해서 붙여넣기 해서 사용하고 있습니다.  알트키를 누른상태에서 숫자패드에서 115F 누르면 입력된다고 하는 제 윈도우10에서는 안되네요. 지식이 짧아서 좀 불편합니다. 할 수 없이 글쓰기 할때는 문자표 실행하고 한글종성필터를 복사해서 붙여넣기 해서 무식(?)하게 사용하고 있습니다.
감사합니다.

**Comment by wkpark** [comment]
음... 이것은 CSS설정을 바꿔야 할 것 같군요.
