### ISSUE TITLE
한글이름으로 된 페이지 삭제방법

### ISSUE THREAD

**Issue by elviraskim** [wkpark/moniwiki#118]
안녕하세요 ?
영문이름이나 숫자이름으로 된 페이지는 삭제가 됩니다.
쪽지우기을 클릭해서 비밀번호 넣고 지웁니다.
그런데 한글이름으로 된 페이지를 삭제하려면
"위키관리자만 페이지를 삭제할 수 있습니다."
삭제가 되질 않습니다. 
생각해보니 이전버젼에도 그랬습니다.
제가 위키설정을 잘못해서 그런가요.
현재 위키버젼 1.2.3 을 사용하고 있습니다.
데스크탑 위키에서도 그렇고 카페21 계정에 설치한 것도
한글이름 페이지는 삭제가 안됩니다.
도와주세요. 무지한 초보자를

**Comment by raygerious1234** [comment]
아무래도 버전 문제인 것 같습니다
버전을 올리십시오
