### ISSUE TITLE
PHP 7 지원

### ISSUE THREAD

**Issue by wkpark** [wkpark/moniwiki#120]
모니위키는 아직도 PHP 4.0 지원 관련 코드가 널려있습니다...
최소 PHP 5 지원을 유지하도록 하되 PHP7에 필수적인 부분은 고쳐나가도록 하겠습니다~

**Comment by raygerious1234** [comment]
php 5.6 이상으로 하니까 에러가 나더라고요.....

**Comment by raygerious1234** [comment]
모니위키 망했음요ㅠ

**Comment by raygerious1234** [comment]
걍 미디어위키 써야지

**Comment by icehit3** [comment]
저도 옮길까 고민 중입니다.  
PHP7 정식 지원은 언제일지...기약이 없으니깐요.

**Comment by raygerious1234** [comment]
성능이 더 좋은 미디어위키 쓰는 게  
답일듯요
