### ISSUE TITLE
설치 페이지

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#131]
설치 페이지(monisetup.php)에서 우측 상단의 언어를 변경해도 언어가 변경되지 않습니다.

**Comment by Goodsims** [comment]
저도 같은 문제가 발생하고 있습니다ㅠㅠ

**Comment by wkpark** [comment]
모니위키 사이트가 소실된 이후로 패키징 된 tarball로 설치하지 않는 경우에 발생할 수 있는 문제로군요.
(사이트는 소실되었으나 당시 하드디스크는 다행이 무사합니다)

일단 간략히 요약하자면
1. `gettext` 필요.
2.  `cd locale; sh update-makefile.sh; make` (로케일 파일 생성) - 패키징된 tarball의 경우 포함되어 있음.
3.  웹페이지 상에서 `monisetup.php` 열기
