### ISSUE TITLE
설치 오류

### ISSUE THREAD

**Issue by Goodsims** [wkpark/moniwiki#133]
000webhost 에서 모니위키를 설치하려 monisetup.php 에 들어가면 아래와 같은 경고문? 이 출력됩니다.

Warning: require_once(/storage/ssd5/597/12535597/public_html/wiki/lib/confutils.php): failed to open stream: No such file or directory in /storage/ssd5/597/12535597/public_html/wiki/monisetup.php on line 22

Fatal error: require_once(): Failed opening required '/storage/ssd5/597/12535597/public_html/wiki/lib/confutils.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd5/597/12535597/public_html/wiki/monisetup.php on line 22

이 문제는 지금 전체에서 나타나는 문제인가요?

**Comment by wkpark** [comment]
우분투 18.04 + php7.2 + apache2 에서 git 버전을 설치해보니 이와 같은 오류가 뜨지 않네요.
호스팅업체에서  제한을 걸어놓은 것 같습니다.
