### ISSUE TITLE
[[duedate()]] 에서 문제발생

### ISSUE THREAD

**Issue by elviraskim** [wkpark/moniwiki#135]
수고많으십니다

윈도우에서 만들어주신 apmoniwiki 사용하고 있습니다

PHP Version	5.2.13 (Windows U53X build)

MoniWiki Version	Release 1.2.6-GIT [Revision: 1.2000 ]

HTTP Server Version	Apache 2.2.22

[[duedate(20371225)]]  하면 6185 day(s) left until 2037-12-25.

매크로에서 2037년까지는 제대로 나오는데 

[[duedate(20381225)]]  하면 18644 day(s) passed from 1970-01-01.

2038년이후는 1970-01-01로 바뀌어 계산됩니다.

이 문제 어떻게 하면 해결할수 있을까요?

**Comment by revi** [comment]
[2038년 문제](https://ko.wikipedia.org/wiki/2038년_문제) 같네요.

**Comment by elviraskim** [comment]
서버에 올린 위키는

PHP Version | 5.6.x (Linux 2.6.32-754.35.1.el6.x86_64 SMP)

Release 1.2.6-GIT [Revision: 1.2000 ]

Apache/2.2.15

에는 제대로 작동합니다

그럼 PHP 5.6 에 있는 파일중에 어떤파일을 PHP 5.2 폴더에 복사하면 될까요?

모니위키용으로 만들어준 윈도우용 마이크로아파치 라서 그런지

PHP 5.6 압축을 풀어 몽땅 덮어씌우니 에러가 납니다.

윈도우용 마이크로 아파치에 어떻게 해야 하는지 알려주시면 감사하겠습니다.

**Comment by YJSoft** [comment]
@elviraskim 서버와 무관하게 모니위키에서 2038년 문제가 있는 함수를 사용해 발생하는것으로 모니위키 소스코드만 DateTime 클래스 사용하도록 수정하면 됩니다.

**Comment by elviraskim** [comment]
> @elviraskim 서버와 무관하게 모니 위키에서 2038 년 문제가있는 함수를 발생하는 것으로 모니 위키 소스 코드 만 DateTime 클래스를 사용하여 수정하면됩니다.

답변 감사합니다
저는 php 를 잘 모릅니다 
시간이 허락하시면 소스에서 무엇을 어떻게 수정하면 되는지 알려주시면 감사하겠습니다.
 
function macro_DueDate($formatter,$value) {
  $time= localtime(time(),true);

  $day= $time['tm_mday'];
  $month= $time['tm_mon']+1;
  $year= $time['tm_year']+1900;
  $now_val= strtotime($year.sprintf("%02d%02d",$month,$day));

  $date_val=$value;

  if (strlen($value) == 2) {
    if ((int) $value < $time['tm_mday'])
      $month+=1;
    if ($month > 12) {
      $year+=1; $month=1;
    }
    $date_val=$year.sprintf("%02d%s",$month,$value);
  } else if (strlen($value) == 4) {
    if ($value < $month.$day)
      $year++;
    $date_val=$year.$value;
  } else if (strlen($value) != 8) {
    return "[[DueDate($value error!)]]";
  }

  $time_val= strtotime($date_val);
  $time_diff= (int) (($time_val - $now_val)/86400);
  
  $date = gmdate("Y-m-d", $time_val + $formatter->tz_offset);

  if  ($time_diff > 0)
     $msg=sprintf(_("%d days left until %s."), $time_diff, $date);
  else if ($time_diff == 0)
     $msg=_("It's today.");
  else
     $msg=sprintf(_("%d days passed from %s."), abs($time_diff), $date);

  return $msg;
// vim:et:sts=4:
}

**Comment by YJSoft** [comment]
@elviraskim 저는 바빠서 수정까지는 못해드릴것 같고... 모니위키 업데이트 될때까지 기다리셔야 할것 같습니다.

**Comment by elviraskim** [comment]
> @elviraskim 저는 바빠서 수정까지는 못해드릴것 같고... 모니위키 업데이트 될때까지 기다리셔야 할것 같습니다.

할줄 모르면서 그냥 짖어봤군요 !~

**Comment by YJSoft** [comment]
@elviraskim 하려면 할수는 있습니다만... 돈이라도 주실건가요? 굉장히 무례하시네요.
