### ISSUE TITLE
PHP7 에서 설치에러

### ISSUE THREAD

**Issue by elviraskim** [wkpark/moniwiki#136]
이번에 2038년에러로 PHP7로 업그레이드 해보려고 하는데 

이것도 잘 안됩니다 (무지해서)

마이크로아파치 MicroApache 2.4.46 + PHP7.4.12 구해서 설치해 보는데  

Deprecated: Array and string offset access syntax with curly braces is deprecated in G:\www\moniwiki\lib\confutils.php on line 173

Deprecated: Array and string offset access syntax with curly braces is deprecated in G:\www\moniwiki\lib\confutils.php on line 173

Fatal error: Uncaught Error: Call to undefined function bindtextdomain() in G:\www\moniwiki\monisetup.php:733 Stack trace: #0 G:\www\moniwiki\monisetup.php(752): initlocale('ko_KR.UTF-8', 'UTF-8') #1 {main} thrown in G:\www\moniwiki\monisetup.php on line 733

이런 에러메시지가 나옵니다.
해결방법 좀 알려주십시오.

**Comment by icehit3** [comment]
5.x버전 써야 합니다. PHP버전업하면서 기존 함수? 작동안하는게 있어서 대대적으로 뜯어고쳐야 합니다. wkpark님이 작업중이라던데...아직은 업데이트 소식이 없네요

**Comment by YJSoft** [comment]
PHP7로 업그레이드하신다고 생기는 오류가 없어지지는 않습니다. 오히려 더 생긴다면 생길 뿐이죠.

**Comment by elviraskim** [comment]
> PHP7로 업그레이드하신다고 생기는 오류가 없어지지는 않습니다. 오히려 더 생긴다면 생길 뿐이죠.

알지도 못하면서 그만 짖어요 !~

**Comment by YJSoft** [comment]
참고로 PHP 7 관련 이슈도 이미 있습니다(#120)

**Comment by YJSoft** [comment]
계속해서 해결방법 알려달라 하시는데 모니위키 개발자가 잠수중인 지금 상황에서 개발자가 돌아오지 않는한 상황은 해결되지 않습니다. 답변 다는 것도 순전히 호의에서 하는것이지 제 의무가 아니므로 무례한 답변 하셔도 상황 달라지지 않습니다.

**Comment by icehit3** [comment]
elviraskim님께는 개발이력이 활발한 다른 위키 (도쿠위키, 미디어위키 등) 사용을 권합니다. 모니위키는 개발자분께서 생업 등의 이유로 개발을 중단한 상황입니다. 저같은 몇몇 분들만 구시스템 (PHP5.x)에서 돌리고 있을뿐...나머지 분들은 다 떠났습니다. 문제가 생기더라도 스스로 해결할 수 밖에 없습니다.

**Comment by elviraskim** [comment]
친절한 답변 감사드립니다.
희망이 없다고 생각하고 질문을 올렸지만 …
어제부터 도쿠위키가 마이크로아파치를 포함하고 있어서
다운로드하여설치해서 시험중에 있습니다.
다시 한번 친절할 답변 감사드립니다.

그런데 혹시 (구글링을 아무리해도 찾을수가 없네요)
마이크로아파치(apache 2.4.25 & php 5.6.30)  다운로드 할수있는 방법이나
마이크로아파지 제작하는 방법을 알려주는 사이트 아시면 부탁드립니다
다시 한번 친절한 답변 감사드립니다.

항상 건강하시고 행복하세요 !~

2021년 1월 22일 (금) 오후 1:49, icehit3 <notifications@github.com>님이 작성:

**Comment by icehit3** [comment]
질문하신 부분은 저도 잘 모르겠습니다. 

마지막으로 조언을 드리면...
전문가가 만들어놓은 걸 그대로 쓰는게 좋아요. 

그런건 제 입맛에 안맞아서 호스팅서비스에 직접 모니위키를 설치했지만...
안정화되기 전까지 무한ㄴ 삽질을 했습니다. 
개발자님 피드백을 받을 수 있는 상황이었는데도요

**Comment by elviraskim** [comment]
빠른 답변 감사드립니다

조언에 저도 동감입니다
모니위키 0.7 시절(2003년)부터 저는 HTML밖에 모르는데 개인노트로 사용하였습니다
어째든 도쿠위키로 갈아타기로 마음먹고 작업중입니다
다양한 플러그인이 놀라고 간단한 노트가 아니고 데이터베이스까지 가능한 신세계입니다
이번 2038년 사건으로 모니위키에서 도쿠위키로 갈아타면서 신세계로 갑니다

다시한번 친절한 답변에 감사드립니다
항상 건강하시고 행복하세요 !~


2021년 1월 22일 (금) 오후 3:05, icehit3 <notifications@github.com>님이 작성:

**Comment by wkpark** [comment]
어느새 PHP7.4를 넘어 php8이 나오고 있군요. 시간 참 빨리 흐릅니다.
php7.x 지원 관련 문제 + 마이크로아파치+php7.x 패키징 등등을 쉬엄쉬엄 하도록 하겠습니다.
이슈는 이미 닫혔지만 댓글달아봅니다.

**Comment by elviraskim** [comment]
제작자님께서 댓글주셔서 감사합니다
모니위키 오랬동안 사용해서 익숙하고 자료도 많아서 미련이 많습니다
제작자님께서 시간이 나시는데로 업그레이드 해주시면 감사할 따름입니다
저는 DueDate 매크로에 사용된 함수의 2038년 문제만 해결되고
마이크로아파치+7.x 패키징에 php 7.x 지원되는 모니위키면 감사할 따름입니다
제작자님 건강하시고 가족과 함께 행복하십시오!~
