### ISSUE TITLE
Report vulnerability

### ISSUE THREAD

**Issue by enferas** [wkpark/moniwiki#137]
Hello,

I would like to report for a vulnerability.

Can I report it here or you prefer if I send it by email ?

**Comment by YJSoft** [comment]
I think you should do below.

1. Send email to `wkpark@gmail.com` (this is @wkpark 's mail address)
2. Wait for reply
3. If no reply received(or no responce to this issue) within 14 days, upload detail to here to anyone can patch vulnerability.
