### ISSUE TITLE
안녕하세요. 문의 드릴 것이 있어서 이슈를 올립니다.

### ISSUE THREAD

**Issue by surplus-dev** [wkpark/moniwiki#138]
안녕하세요. 다름이 아니라 모니위키에서 다른 위키 엔진으로 연동되는 마이그레이션 툴을 만들어보고자 해서 연락드렸습니다.

다른 이유는 아니고 저도 과거에 모니위키를 이용했던 유저로써 모니위키가 점점 업데이트 없이 풍화되는 것이 안타깝다고 생각해서 그렇습니다

물론 모니위키는 GPLv2를 사용하는 오픈소스이지만 원작자의 의견을 반영하고자 해서 이렇게 이슈를 올립니다

**Comment by wkpark** [comment]
수고 많으십니다

여력이 없어서 거의 방치상태네요

확인해보도록 하겠습니다.

(PHP 7.x / PHP 8.x 지원이라도 확인해야 하는데...)
