### ISSUE TITLE
colbgcolor 지원

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#146]
현재 rowbgcolor는 지원되고 있지만 colbgcolor는 지원되지 않습니다.

colbgcolor도 지원했으면 합니다.

**Comment by wkpark** [comment]
http://moinmo.in/HelpOnTables 이에 의하면 `colbgcolor` 문법은 아예 없습니다.
(참고로 `rowbgcolor`문법도 모니위키 초기 버전에서는 지원 안했습니다)

실제 테이블로 변환이 되면 `<tr>` 태그의 `bgcolor`를 세팅하기만 하면 그것이 `rowbgcolor`가 됩니다.

HTML 스펙이 어떤지 궁금해서 찾아보니...
`HTML` 스펙에 `<colgroup>` 및 `<col>`이 있었네요...
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup

파서에서 `colbgcolor` 문법을 사용한 경우, `<colgroup><col>...` 지정하여 bgcolor 넣으면 될 것으로 보입니다만...
(다음 버전에 `colbgcolor` 지원을 고민해봐야 할 것 같습니다.)

----

다만, html 태그만이 아닌 css로 확장해서 얘기하자면,
~~~.css
   th:nth-child(2n), td:nth-child(2n) {
    background-color: #bbdefb;
  }
~~~
위와 같은 식으로 css레벨에서 특정 컬럼 배경색을 지정하는 것은 지금도 가능합니다.

다만, 위에서 말씀드렸던 것처럼 `css`레벨에서 사이트 전체에 적용가능한 방법이며, `colbgcolor` 사용 없이 지금도 여전히 쓰실 수 있습니다. (이 경우 세밀한 컨트롤은 할 수 없겠고요.)

----
어떤 상황에서 `colbgcolor`를 넣고싶은 것인지 시간되시면 설명 부탁드리겠습니다.

**Comment by NbverHub** [comment]
![image](https://user-images.githubusercontent.com/13084942/199492840-3883183e-33b2-4273-a098-4b72cffafcf1.png)
위와 같은 표를 만들 때 현재로선 각 표마다 <bgcolor=#000000>을 넣어야 하는데, colbgcolor가 있다면 문법 하나로 해결할 수 있어 편할 것 같기 때문입니다. 즉 여러 열의 표가 있을 때 한 열의 색을 편하게 통일해서 지정할 수 있었으면 해서요.

**Comment by wkpark** [comment]
> ![image](https://user-images.githubusercontent.com/13084942/199492840-3883183e-33b2-4273-a098-4b72cffafcf1.png) 위와 같은 표를 만들 때 현재로선 각 표마다 <bgcolor=#000000>을 넣어야 하는데, colbgcolor가 있다면 문법 하나로 해결할 수 있어 편할 것 같기 때문입니다. 즉 여러 열의 표가 있을 때 한 열의 색을 편하게 통일해서 지정할 수 있었으면 해서요.

제시하신 형태를 `<colgroup><col>` 형태로 표현해보려 해도 제대로 할 수 없네요.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/colgroup

일단 가장 단순하 형태의 구현은 가능하다는 것을 PR로 올려두었습니다. `<colgroup>`을 제대로 이해한 후에 좀 더 고쳐야 할  듯
