### ISSUE TITLE
rcs 관련 문의

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#156]
만약 서버나 호스팅 문제로 RCS가 지원되지 않아 RcsLite를 사용하다가 RCS를 지원하는 서버로 옮길 경우, RcsLite를 통해 기록된 로그들을 RCS를 통해 사용할 수 있는지, 사용할 수 있다면 어떻게 해야하는지 궁금합니다.

**Comment by wkpark** [comment]
RCSLite는 RCS와 문제 없이 호환됩니다.
`config.php`서 다음 줄을 찾아 없애주시면 (혹은 `#`를 줄 맨 앞에 붙여주면) 기본 버전 컨트롤 방식인 `rcs`가 사용됩니다.

* `$version_class= 'RcsLite';` => `#$version_class= 'RcsLite';`

호스팅 서버에서 `popen()` 사용을 막은 것이 아니라면 `rcs`를 직접 컴파일 하시거나 `rcs` 실행파일만 다운로드 해서
설치해서 사용하실 수도 있습니다.

예를 들어, rcs 실행파일인 `ci, co, rcs, rlog, rcsdiff` 등등을 모니위키 설치 디렉토리에 `bin/` 이라는 디렉토리를 만들어서 복사해 넣은 후에 `config.php`에서 `$path` 변수를 다음과 같은 식으로 잡아주시면 됩니다.
 * `$path='./bin:/usr/local/bin:/usr/bin:/bin'`; #
