### ISSUE TITLE
우분투22.04: Moniwiki 1.2.9 버젼부터 기존의 "[[TableOfContents]]" 명령 동작 불가

### ISSUE THREAD

**Issue by leemgs** [wkpark/moniwiki#161]
1.2.9 버젼부터 기존의 "[[TableOfContents]]" 명령이 동작이 안먹히고 있습니다. 
요 메크로가  많은 내용들의 TOC를 한번에 젤먼저  열람하고자 할때  상당히  좋은 기능이라 아쉽습니다. 

해결 방법이 없을까요?

## 재현 환경
* PHP Version:	8.1.x (Linux 5.15.0-75-generic SMP)
* MoniWiki Version	Release :1.3.0-GIT [Revision: 1.2093 ]
* HTTP Server Version:	Apache/2.4.52
 
 
```bash

invain@u2204:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
invain@u2204:~$ uname -a
Linux u2204 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
invain@u2204:~$


```
## 재현 시나리오
* https://github.com/wkpark/moniwiki/blob/bde8167d1b3198b918d18f2db503f3ed48ac60ed/wikilib.php#L5489

새로운 moniwki 페이지를 생성한후에 다음과 같이 "[[TableOfContents]]" 명령을 사용하는
segment 섹션 2개를 만들어본다. 
이때 [[TableOfContents]] 이명령을 사용하면 위키페이지가 empty가 보인다. 
그래서 이때 "edit"를 누르고 나서. [[TableOfContents]] 매크로 명령을 제거해야 한다. 

```bash
[[TableOfContents]]
== Segment register1 ==
 * Logical1
 * Logical2
== Segment register2 ==
 * Logical1
 * Logical2
```

**Comment by wkpark** [comment]
알려주셔서 감사합니다. PHP7에서는 작동하는 것을 보니 deprecated된 함수가 사용된 것 같습니다.
방금 확인해보니 `join()`때문인 것 같네요

**Comment by wkpark** [comment]
감사합니다!
