### ISSUE TITLE
문의

### ISSUE THREAD

**Issue by kaliubuntu0206** [wkpark/moniwiki#167]
안녕하세요

모니위키 관련해서 문의드릴것이 있는데요

혹시 연락처나 이메일이 있으실까요?

감사합니다.

**Comment by NbverHub** [comment]
README.md에 적혀있는 메일로 보내시면 되지 않을까 싶네요.

**Comment by kaliubuntu0206** [comment]
@NbverHub 이미 메일을 보냈으나 한달 넘게 회신이 없으시네요

**Comment by wkpark** [comment]
문의하실 내용이 뭔가요? 이메일 뒤져봐도 없어서 말았던 것 같은데,
다시 찾아보니 문의 내용은 없고 문의 메일 보내도 되냐는 내용의 메일이 한통 와있었군요. 본 기억이 나는것도 같네요.
(제목에 "안녕하세요"라고만 되어있고 내용은 한줄짜리)

남이 보기 곤란한 내용이 아니면 그냥 여기에 올리시면 추적 및 관리가 됩니다.
남이 보기 곤란한 내용이라면 제목과 내용을 구체적으로 보내주세요.
한줄짜리 메일에 답변하는 일은 없다고 보시면 됩니다.

**Comment by kaliubuntu0206** [comment]
@wkpark 방금 회신 보내드렸습니다. 감사합니다.
