### ISSUE TITLE
PHP 8.x  사용자들을 위해 v1.2.10 릴리즈  하면 좋겠습니다. 

### ISSUE THREAD

**Issue by leemgs** [wkpark/moniwiki#168]
이제 대부분의 리눅스 배포판들이 PHP 8.x 버젼으로 이동하였기 때문에 
이제 moniwki도 PHP 8.x  사용자들을 위해 v1.2.10 릴리즈  하면 좋겠습니다. 
v1.2.10를 한번 단행해주세요. ^^

* 예제:
https://github.com/wkpark/moniwiki/releases/tag/v1.2.10

**Comment by wkpark** [comment]
이제야 업데이트 했습니다
