### ISSUE TITLE
WantedPages 매크로 개선

### ISSUE THREAD

**Issue by sappho192** [wkpark/moniwiki#50]
https://namu.wiki/NeededPages
나무위키에는 위와 같이 역링크는 존재하는데 작성은 되어있지 않은 문서의 목록을 보여주는 페이지를 지원하고 있습니다. 모니위키에도 이걸 매크로로 지원하면 좋을 것 같아요.

**Comment by wkpark** [comment]
`[[WantedPages]]` 매크로가 해당 기능을 합니다.

단, 이 매크로는 느립니다. 작은 개인 위키에서는 별 문제 없겠지만
좀 더 효율적으로 바꿔야 하죠.

**Comment by sappho192** [comment]
앗 정말 있었군요! 감사합니다 ㅎㅎ...
그러면 [Help On Macros](http://moniwiki.kldp.net/main/HelpOnMacros)와 [MoniWikiMacros](http://moniwiki.kldp.net/main/HelpOnMacros)에 해당 매크로에 대한 설명이 없던데 반영해주실 수 있나요?

그리고 전체 페이지를 돌면서 검색하는거라면 페이지 요청이 있을 때 마다 검색을 하지 말고 사용자가 지정한 옵션(검색하는 시각, 주기 등)에 맞춰 한 번씩만 해당 정보를 만들 수 있도록 하면 좋을 것 같은데, 어떻게 생각하세요?

**Comment by wkpark** [comment]
> 그리고 전체 페이지를 돌면서 검색하는거라면 페이지 요청이 있을 때 마다 검색을 하지 말고 사용자가 지정한  옵션(검색하는 시각, 주기 등)에 맞춰 한 번씩만 해당 정보를 만들 수 있도록 하면 좋을 것 같은데, 어떻게 생각하세요?

좋은 생각이십니다~
이 매크로는 2003년에 만들어졌지만, 잘 사용되어지지 않는다는 이유로 별다른 개선이 없었습니다
이번에 속도적인 측면에서 개선해보도록 하겠습니다~

**Comment by sappho192** [comment]
감사합니다. 나무위키에서 해당 페이지를 통해 역링크가 없는 항목들을 개설하고 싶은 동기가 많이 생겼었는데 모니위키엔 이미 있었던 기능이라니 너무 빛을 발하지 못한 것 같네요. ㅜㅜ

**Comment by wkpark** [comment]
별말씀을요~ 제안 감사합니다~!!

**Comment by sappho192** [comment]
WantedPages 플러그인에서 항목을 찾아낼 때 몇 가지 버그가 있는 것 같습니다.
[제가 만들고 있는 위키](http://inha.wiki/wiki.php/%EC%9E%91%EC%84%B1%EC%9D%B4%20%ED%95%84%EC%9A%94%ED%95%9C%20%ED%8E%98%EC%9D%B4%EC%A7%80)를 보시면 인터위키 링크도 찾아내는 것 같네요.  
그리고 중괄호 세 쌍 안에 있는 내용도 찾아내는 것 같은데 예외처리를 해두셔야 할 것 같아요!

**Comment by wkpark** [comment]
일단 대규모 위키에서도 문제가 없도록 수정하였으며,
약간 보기 좋게 바꿔보았습니다~
