### ISSUE TITLE
마크업 무시 문법에 |이 붙을 때 정상적으로 처리되지 않습니다.

### ISSUE THREAD

**Issue by senior9324** [wkpark/moniwiki#53]
http://rigvedawiki.net/HelpOnTables?action=recall&rev=1.34
http://threadiki.80port.net/wiki/wiki.php/WikiSandBox?action=recall&rev=1.58

마크업 무시 문법에 |가 붙어 {{{| 로 시작하는 경우 {{{{#!wiki .closure로 바뀌어 나오면서 그 뒤로 모든 문법이 무시됩니다.

**Comment by wkpark** [comment]
`{{|` 문법은 모니위키 기본 파서 엔진에서 완전히 제거되었습니다.
리그베다위키에서 이 문법을 그대로 쓸 수 있게끔 간단한 대치 문법을 쓰는데 그게 오작동하는 것입니다.

이 이슈는 리그베다 한정적인 이슈이므로 닫도록 하겠습니다. 관련 질문있으면 질문하시기 바랍니다~
