### ISSUE TITLE
통계 기능 외

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#55]
wikistat 등 통계기능이 추가되었는데 기존에 counter랑 연관해서 통계 기능을 제공하면 어떨까 합니다.

perl이 지원되지 않는 경우에는 조회수 db를 업데이트 하는 방법이 없을까요?

**Comment by wkpark** [comment]
생각해보니 그렇네요! wikistat은 현재 대규모 위키에 대해서 최적화 되어있지만, 개인위키에서도 통계 기간을 늘리면 (한달을 간격으로 한다거나) 예쁜 그래프를 볼 수 있게 됩니다.

----
perl이 아니고 PHP의 dba를 지원하면 조회수를 사용할 수 있습니다. 질문은 네이버쪽에서 해주시는 것이 낫습니다~

**Comment by wkpark** [comment]
#89 에서 비슷한 방식의 그래프를 지원하게 되었습니다.
