### ISSUE TITLE
저작권 침해 판별을 위한 기능

### ISSUE THREAD

**Issue by wkpark** [wkpark/moniwiki#67]
http://new.wikibbs.net/bug/16488 에서 집토끼님이 제안하신 기능을 추가할 예정입니다.

https://github.com/wikigit/Duplication-Detector

**Comment by revi** [comment]
Wikigit의 버전보다는 https://github.com/earwig/copyvios 요걸 베이스로 삼는 게 낫지 않았을까 싶기도 합니다. 저건 3년전에 개발이 중단된 것 같아 보이고요. https://tools.wmflabs.org/copyvios/ 서 돌아가는 버전도 earwig 겁니다.

**Comment by wkpark** [comment]
잘 아시겠지만 copyvios는 파이썬 소스라서 곧바로 써먹을 수 없었고요
wikigit 버전은 PHP라서 소스 수정이 거의 없이 그대로 사용하였습니다~
