### ISSUE TITLE
1.2.5 정식 버전은 언제쯤 나올까요?

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#74]
근래 잦은 업데이트로 나름 즐거움을 누리고 있습니다만, 귀차니즘(...) 덕분에 판올림 할때마다 업데이트 하기로 결심한지라 문의드립니다.

p.s
paper 테마 쪽에 올린 이슈도 확인해주세요.

**Comment by wkpark** [comment]
moniwiki.net 개발 서버를 살려야 하는데... -_-;;
거기 남아있는 작업분도 상당하거든요..
(그 이외의 개발은 현재 리그베다 서버에서 진행중입니다)

**Comment by rotkqkffus** [comment]
만약에 살리면 미러 사이트를 만드는것은 어떤가요?
