### ISSUE TITLE
XSS 필터링

### ISSUE THREAD

**Issue by wkpark** [wkpark/moniwiki#8]
현재 모니위키는 XSS대처를 하지 않고 있습니다.

문서 자체에 html을 직접 넣을 수 있으며,
이를 여과하지 않고 그대로 랜더링하기때문에 마음만 먹으면 XSS 어택이 가능합니다.

HTML 프로세서에 대해서 XSS 필터링을 기본으로 적용합니다.
스크립트를 그대로 저장하지만, 이를 렌더링하는 단계에세 필터링을 하는 것입니다.
물론 개인 사용자의 경우에 대해서는 `$no_xss_filter=1;` 옵션을 통해서 XSS 필터링을 끌 수 있습니다.

**Comment by KyulingLee** [comment]
그럼 1.2.5 버전에서 xss 필터링을 끄면 기존처럼 문서 자체에 html을 넣어도 되는 건가요?

**Comment by wkpark** [comment]
@KyulingLee 넵. 개인 용도로 위키를 사용한다면 그렇게 쓰실 수 있습니다
