### ISSUE TITLE
히스토리 보기에서 일정 버전 이상 히스토리를 볼 수 없는 문제

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#82]
히스토리가 긴(100개 이상) 항목에서 히스토리 다음 버전을 누르다 보면 처음 히스토리 리스트로 되돌아가는 현상이 발생합니다. 관리자 계정으로 로그인해도 동일하네요.

**Comment by wkpark** [comment]
익명의 경우에 히스토리 보기가 30~40개를 최대로 볼 수 있도록 제한을 걸어서 그렇습니다.
95c9fcc3139607

일반 유저로 로그인을 하면 정상적으로 보이셔야 합니다.

혹시 rcslite를 사용하시는지요?

**Comment by NbverHub** [comment]
네 rcslite를 사용하고 있습니다.

**Comment by wkpark** [comment]
아아 그러시군요.
`rcslite`는 원래부터 버전 range 기능이 지원이 안되어서 오래된 버전을 못보던 버그가 예전부터 있었습니다.

RcsLite는 버전 개수가 많이지면 RCS보다 매우 느리고 리소스도 많이 차지하는 단점이 있습니다.
왠만하면 호스팅사에 부탁하여 RCS를 설치한다거나
직접 RCS를 설치해서 세팅해보시기 바랍니다.

관련 요구가 많이 있어서 빌드해놓은 RCS가 있으니 http://dev.naver.com/projects/moniwiki/issue/93836 이곳을 참조해보시기 바랍니다.

네이버보다 이곳이 편리하시면 이곳에 질문하시면 됩니다~
