### ISSUE TITLE
우측 정렬한 표 크기대로 미리보기 상자가 늘어나지 않는 문제

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#84]
내용을 쓰지 않고 우측으로 정렬한 표를 편집창에서 쓰고 미리보기 하면 표가 미리보기 상자를 벗어납니다.

**Comment by wkpark** [comment]
예시를 같이 적어주시면 좋겠습니다~

**Comment by NbverHub** [comment]
예를 들어 다음과 같은 내용만 작성하고 미리보기를 했을 경우에

`||<table align=right> 안녕하세요||`

아래 이미지와 같이 표시됩니다.

![bug](http://i.imgur.com/gN3TgGt.jpg)

내용을 더 적으면 이렇습니다.

![bug](http://i.imgur.com/t76lcre.jpg)

**Comment by wkpark** [comment]
넵 감사합니다~

**Comment by wkpark** [comment]
일단 이것은 미리보기에서만 문제가 되는 것이고, 정상적인 뷰의 경우에 테마를 어떻게 만들었느냐에 따라서 잘 보여줍니다. 렌더러와 크게 상관이 없는 문제라는 것이죠.
물론 렌더러단에서 `clear:both` 혹은 `clearfix`를 적절히 넣어주면 되는 문제이지만,
이를 굳이 해결하지는 않도록 합니다.

- - - - -
이것과 상관 없이 Preview 박스의 최소 크기를 적당히 늘려놓으면 이렇게 보이는 현상은 없어집니다.
이를 렌더러에서 해결하기보다는 테마에서 해결하는 것이 나아보이므로 이 이슈는 닫겠습니다.
현재 paper 테마는 preview 최소 크기를 조절해서 이런 현상이 완화되었습니다. 즉, 실제로 `clear:both`를 사용한 것은 아니지만,
