### ISSUE TITLE
template 관련 문제

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#88]
업데이트 이후 실제로 존재하는 Template이 더 많이 있음에도 일부 Template만 하단에 뜹니다.

**Comment by wkpark** [comment]
기본 타이틀 검색에 문제가 있는걸까요?
다음과 같은 식으로 뜨지 않는다는 말씀이시죠?
http://rigvedawiki.net/XXXXXX?action=edit

**Comment by wkpark** [comment]
`config.php` 세팅이 `$template_regex="Template$";` 같은 식으로 되어있는지 확인해보시기 바랍니다.
기본값이 세팅이 되어있지 않으면 `$template_regex="Template$"` 이며 최신 버전에서 정상 작동함을 확인하였습니다.

**Comment by NbverHub** [comment]
해당 설정이 없어서 추가해봤지만 여전히 나오질 않네요. 캐쉬 디렉토리를 지워봐야할까요?

**Comment by wkpark** [comment]
캐시 디렉토리와 상관이 없습니다.

테스트 프로그램을 올려드릴테니 ssh로 로그인해서 한번 테스트해보시기 바랍니다.

(아래 테스트 프로그램을 모니위키 최상위에 올려놓고 (`like.php` 라는 식의 파일 이름으로)
쉘상에서 `$ php like.php` 하시면 됩니다.
출력으로 `Template`로 끝나는 파일 목록이 출력되어야 합니다.
~~~php
<?php
require_once('lib/titleindexer.text.php');
#require_once('lib/PageIndex.php');
require_once('wikilib.php');

$Config = _load_php_vars('config.php');

#$index = new PageIndex();
$index = new TitleIndexer_Text();

$cneedle="(^템플릿:|Template$)";
$cneedle = '[a-z]Template$';
#$cneedle = 'Template$';
#$needle = '케케';
#$cneedle=_preg_search_escape($needle);
#echo $cneedle,"\n";
$ret = $index->getLikePages($cneedle, 0);
print_r($ret);
~~~

**Comment by NbverHub** [comment]
목록이 출력되기는 하네요. 

eAccelerator: Unable to change cache directory /var/cache/php-eaccelerator permissions

이런 오류도 왜인지 같이 뜨고요.

**Comment by wkpark** [comment]
목록이 출력이 된다면..., template 리스트가 출력되지 않는 원인은 다른 곳에 있는 듯 하네요.
아무튼 목록 관련 기능은 정상이라는 것이구요.

eAccelerator 오류는 무시하셔도 됩니다. 일반 유저로 실행하신 경우에 eaccelerator 캐시 디렉토리에 퍼미션이 없어서 경고가 출력되는 것입니다.

**Comment by raygerious1234** [comment]
ㅋ병신새끼
