### ISSUE TITLE
상하위 문서 구분 끄기

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#93]
간간히 문서 이름에 /가 들어가는 경우가 있는데, 의도치 않게 상위/하위 문서로 구분되어서 곤란한 경우가 있습니다.

#nocomment 나 #norating 처럼 명령어를 넣으면 해당 항목에서 상하위 문서 구분이 되지 않게 하면 어떨까 싶습니다.

p.s
더불어 rating 기능이 좀 더 향상되었으면 좋겠네요.

**Comment by wkpark** [comment]
상하위 관계 없는데 문서 이름에 `/ `가 들어가게 되는 경우를 말씀하시는거죠?

일단 모든 위키의 문서는 평면적으로 저장되며  `/` 문자는 상하위 구분자로 역할을 하게 됩니다.

아이콘만 상위로 가는 링크가 나올 뿐만 아니라 `[[../]]` 와 같은 상위로 가는 링크 역시 모두 `/`에 의해 구분되고 작동하게 되지요.

따라서 이 문제는 단순히 상위로 가는 아이콘만 나오지 않는다고 해결되는 문제가 아닌것으로 생각되는군요.
이는 파일 이름에 `/` 문자를 쓸 수 없는 것과 같은 이치입니다. `/` 문자가 들어가면 다른 디렉토리가 되지요.

`SOLIDUS (U+002F)` 문자 말고도 `DIVISION SLASH (U+2215)` 및 `FRACTION SLASH (U+2044)` 문자가 있으니 이를 쓰는 것도 한가지 방법으로 생각됩니다.

**Comment by wkpark** [comment]
그밖에 `/` 문자는 아파치에 의해 특수처리되기때문에 `PATH_INFO` 인수값으로 제대로 넘어오지 않는 문제가 있네요. 즉 `///` 이런 식의 문자열이 `PATH_INFO`로 아예 넘어오지 않습니다. `/` 값으로 전달되는군요.

아무튼 이 이슈는 닫도록 하겠습니다.
