### ISSUE TITLE
recentchange 매크로 관련

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#99]
현재 allusers라는 옵션을 둬서 여러 고친이를 볼 수 있는데, 편집요약은 마지막으로 수정한 사람의 것만 볼 수 있어서 조금 아쉽습니다. allcomment(?)라는 옵션이 있어서, 마지막으로 남겨진 2~3개의 정도의 편집요약을 같이 볼 수 있었으면 합니다.

**Comment by wkpark** [comment]
복수의 편집자를 모두 나열하는 방식은 모인모인에서 지원하길래 그것을 그대로 모방해서 모니위키도 지원하게 된 것입니다.

그러나 https://moinmo.in/RecentChanges 에서 보시는 것같이 여러 사람이 남긴 코멘트를 보이게 하려면 누가 정확히 남긴 것인지 간단하면서도 명료하게 보여줘야 하지만 UI자체가 엉성하게 설계되어 오히려 복잡하게 난해하게 보이더군요.

1. 여러 사람의 코멘트를 같이 보여주려면 코멘트:사용자:남긴 시간 등등을 모두 보여줘야 할 것입니다.
2. 모든 사용자가 로그를 남기지는 않습니다. 코멘트로 인해 오해가 생길 가능성도 있습니다.

이러한 이유로 모든 사람의 로그를 보여주는 방식은 애초부터 고려하지 않았습니다. 다른  사람의 코멘트를 보고싶으면 히스토리를 누르면 되고요.

구체적으로 UI에 대한 아이디어가 있다면 제시해주시면 고맙겠습니다.

**Comment by wkpark** [comment]
별다른 의견이 없으므로 이슈를 닫습니다.
